services:
  api:
    volumes:
      - ../:/app
    environment:
      UV_PROJECT_ENVIRONMENT: /app/.venv-docker
    command: ["/bin/bash", "-c", "uv run alembic upgrade head && uv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
